version: "3.4"

services:
  mongo:
    image: mongo:4.4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
  redis:
    image: redis:alpine
  rabbit:
    image: rabbitmq:3.8.3-alpine
  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
     - discovery.type=single-node
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 80:80
  golium:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/github.com/TelefonicaTC2Tech/golium/
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: eu-west-1
    depends_on:
      - mongo
      - redis
      - rabbit
      - elasticsearch
      - minio
      - httpbin
