version: "3.4"

services:
  redis:
    image: redis:alpine
  rabbit:
    image: rabbitmq:3.8.3-alpine
  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
     - discovery.type=single-node
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 80:80
    # healthcheck:
    #   test: nc -z 127.0.0.1 80
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s
  golium:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/github.com/TelefonicaTC2Tech/golium/
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: eu-west-1
    depends_on:
      - redis
      - rabbit
      - elasticsearch
      - minio
      - httpbin
